### ISSUE TITLE
Collabora Online URL is wrong

### ISSUE THREAD

**Issue by z0rg0n** [BramSuurdje/proxmox-helper-scripts#64]
**Describe the bug**
The **How to install** section for Callabora Online shows an incorrect URL.

**To Reproduce**

1. Go to [https://proxmoxve-scripts.com/scripts?id=Collabora+Online](https://proxmoxve-scripts.com/scripts?id=Collabora+Online).
2. Scroll down to the section that allows you to copy the URL for this helper script.
3. Observe that the URL given is `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/collabora.sh)`.

**Expected behavior**
The URL should be `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/collabora-online.sh)"`

**Comment by BramSuurdje** [comment]
fixed it, thank you!
