### ISSUE TITLE
Collabora Online script doesn't work

### ISSUE THREAD

**Issue by z0rg0n** [BramSuurdje/proxmox-helper-scripts#74]
**Describe the bug**
Pasting the script for Collabora Online into Proxmox doesn't do anything since the URL 'https://github.com/tteck/Proxmox/raw/main/ct/collabora-online.sh' returns a 404 error.

**To Reproduce**
Check the 'https://github.com/tteck/Proxmox/raw/main/ct/collabora-online.sh' link and compare that to what's in the Collabora Onine script. 

**Expected behavior**
Collabora  Online is removed from the available scripts.

**Comment by BramSuurdje** [comment]
It has been removed from the database. thank you!
